# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "landlord"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Scott Tadman"]
  s.date = "2012-01-27"
  s.description = "A command-line tool for managing multiple virtual-host configurations on a web server"
  s.email = "github@tadman.ca"
  s.executables = ["landlord"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/landlord",
    "landlord.gemspec",
    "lib/landlord.rb",
    "lib/landlord/config.rb",
    "lib/landlord/virtual_host.rb",
    "templates/virtual_host.apache.conf",
    "test/expected_results/example_virtual_host.conf",
    "test/expected_results/example_virtual_host_with_aliases.conf",
    "test/expected_results/example_virtual_host_with_redirects.conf",
    "test/helper.rb",
    "test/test_landlord.rb",
    "test/test_landlord_config.rb",
    "test/test_landlord_virtual_host.rb"
  ]
  s.homepage = "http://github.com/twg/landlord"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Web server virtual-host tenant management tool"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<handlebar>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<handlebar>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<handlebar>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

